server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/b2b-account-service
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect:
    database-platform:

application:
  jwt:
    secret: mySecretKeyForMicroservicesE-Commmerce
    expiredTime: 86400000
    refreshExpiredTime: 604800000